# Generated by Django 3.0.5 on 2020-04-04 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=11)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=11)),
                ('status', models.IntegerField(choices=[(0, 'AVAILABLE'), (1, 'IN_USE'), (2, 'RESERVED'), (3, 'UNAVAILABLE'), (4, 'UNKNOWN')])),
            ],
        ),
    ]
