# Generated by Django 3.0.5 on 2020-04-04 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('uid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
