# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cpo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import types_pb2 as types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cpo.proto',
  package='cpsp',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\tcpo.proto\x12\x04\x63psp\x1a\x0btypes.proto\"#\n\x15LocationDetailRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"8\n\x13LocationListRequest\x12\x0e\n\x06offset\x18\x01 \x01(\x05\x12\x11\n\tnum_items\x18\x02 \x01(\x05\"R\n\x17LocationCreationRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x0b\n\x03lon\x18\x03 \x01(\x01\x12\x0b\n\x03lat\x18\x04 \x01(\x01\x32\xce\x01\n\tLocations\x12@\n\x0fGetLocationList\x12\x19.cpsp.LocationListRequest\x1a\x0e.cpsp.Location\"\x00\x30\x01\x12<\n\x0bGetLocation\x12\x1b.cpsp.LocationDetailRequest\x1a\x0e.cpsp.Location\"\x00\x12\x41\n\x0e\x43reateLocation\x12\x1d.cpsp.LocationCreationRequest\x1a\x0e.cpsp.Location\"\x00\x62\x06proto3'
  ,
  dependencies=[types__pb2.DESCRIPTOR,])




_LOCATIONDETAILREQUEST = _descriptor.Descriptor(
  name='LocationDetailRequest',
  full_name='cpsp.LocationDetailRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='cpsp.LocationDetailRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=67,
)


_LOCATIONLISTREQUEST = _descriptor.Descriptor(
  name='LocationListRequest',
  full_name='cpsp.LocationListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='offset', full_name='cpsp.LocationListRequest.offset', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_items', full_name='cpsp.LocationListRequest.num_items', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=125,
)


_LOCATIONCREATIONREQUEST = _descriptor.Descriptor(
  name='LocationCreationRequest',
  full_name='cpsp.LocationCreationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='cpsp.LocationCreationRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='cpsp.LocationCreationRequest.address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lon', full_name='cpsp.LocationCreationRequest.lon', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lat', full_name='cpsp.LocationCreationRequest.lat', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=209,
)

DESCRIPTOR.message_types_by_name['LocationDetailRequest'] = _LOCATIONDETAILREQUEST
DESCRIPTOR.message_types_by_name['LocationListRequest'] = _LOCATIONLISTREQUEST
DESCRIPTOR.message_types_by_name['LocationCreationRequest'] = _LOCATIONCREATIONREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LocationDetailRequest = _reflection.GeneratedProtocolMessageType('LocationDetailRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONDETAILREQUEST,
  '__module__' : 'cpo_pb2'
  # @@protoc_insertion_point(class_scope:cpsp.LocationDetailRequest)
  })
_sym_db.RegisterMessage(LocationDetailRequest)

LocationListRequest = _reflection.GeneratedProtocolMessageType('LocationListRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONLISTREQUEST,
  '__module__' : 'cpo_pb2'
  # @@protoc_insertion_point(class_scope:cpsp.LocationListRequest)
  })
_sym_db.RegisterMessage(LocationListRequest)

LocationCreationRequest = _reflection.GeneratedProtocolMessageType('LocationCreationRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONCREATIONREQUEST,
  '__module__' : 'cpo_pb2'
  # @@protoc_insertion_point(class_scope:cpsp.LocationCreationRequest)
  })
_sym_db.RegisterMessage(LocationCreationRequest)



_LOCATIONS = _descriptor.ServiceDescriptor(
  name='Locations',
  full_name='cpsp.Locations',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=212,
  serialized_end=418,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetLocationList',
    full_name='cpsp.Locations.GetLocationList',
    index=0,
    containing_service=None,
    input_type=_LOCATIONLISTREQUEST,
    output_type=types__pb2._LOCATION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetLocation',
    full_name='cpsp.Locations.GetLocation',
    index=1,
    containing_service=None,
    input_type=_LOCATIONDETAILREQUEST,
    output_type=types__pb2._LOCATION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateLocation',
    full_name='cpsp.Locations.CreateLocation',
    index=2,
    containing_service=None,
    input_type=_LOCATIONCREATIONREQUEST,
    output_type=types__pb2._LOCATION,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOCATIONS)

DESCRIPTOR.services_by_name['Locations'] = _LOCATIONS

# @@protoc_insertion_point(module_scope)
