# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import protocol.proto.cpo_pb2 as cpo__pb2
import protocol.proto.types_pb2 as types__pb2


class LocationsStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLocationList = channel.unary_stream(
                '/cpsp.Locations/GetLocationList',
                request_serializer=cpo__pb2.LocationListRequest.SerializeToString,
                response_deserializer=types__pb2.Location.FromString,
                )
        self.GetLocation = channel.unary_unary(
                '/cpsp.Locations/GetLocation',
                request_serializer=cpo__pb2.LocationDetailRequest.SerializeToString,
                response_deserializer=types__pb2.Location.FromString,
                )
        self.CreateLocation = channel.unary_unary(
                '/cpsp.Locations/CreateLocation',
                request_serializer=cpo__pb2.LocationCreationRequest.SerializeToString,
                response_deserializer=types__pb2.Location.FromString,
                )


class LocationsServicer(object):
    """Missing associated documentation comment in .proto file"""

    def GetLocationList(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLocation(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateLocation(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LocationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLocationList': grpc.unary_stream_rpc_method_handler(
                    servicer.GetLocationList,
                    request_deserializer=cpo__pb2.LocationListRequest.FromString,
                    response_serializer=types__pb2.Location.SerializeToString,
            ),
            'GetLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLocation,
                    request_deserializer=cpo__pb2.LocationDetailRequest.FromString,
                    response_serializer=types__pb2.Location.SerializeToString,
            ),
            'CreateLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateLocation,
                    request_deserializer=cpo__pb2.LocationCreationRequest.FromString,
                    response_serializer=types__pb2.Location.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cpsp.Locations', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Locations(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def GetLocationList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/cpsp.Locations/GetLocationList',
            cpo__pb2.LocationListRequest.SerializeToString,
            types__pb2.Location.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cpsp.Locations/GetLocation',
            cpo__pb2.LocationDetailRequest.SerializeToString,
            types__pb2.Location.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cpsp.Locations/CreateLocation',
            cpo__pb2.LocationCreationRequest.SerializeToString,
            types__pb2.Location.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
