# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msp.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protocol.proto.types_pb2 as types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='msp.proto',
  package='cpsp',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\tmsp.proto\x12\x04\x63psp\x1a\x0btypes.proto\" \n\x12TokenDetailRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"5\n\x10TokenListRequest\x12\x0e\n\x06offset\x18\x01 \x01(\x05\x12\x11\n\tnum_items\x18\x02 \x01(\x05\"1\n\x14TokenCreationRequest\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t2\xb0\x01\n\x06Tokens\x12\x37\n\x0cGetTokenList\x12\x16.cpsp.TokenListRequest\x1a\x0b.cpsp.Token\"\x00\x30\x01\x12\x33\n\x08GetToken\x12\x18.cpsp.TokenDetailRequest\x1a\x0b.cpsp.Token\"\x00\x12\x38\n\x0b\x43reateToken\x12\x1a.cpsp.TokenCreationRequest\x1a\x0b.cpsp.Token\"\x00\x62\x06proto3'
  ,
  dependencies=[types__pb2.DESCRIPTOR,])




_TOKENDETAILREQUEST = _descriptor.Descriptor(
  name='TokenDetailRequest',
  full_name='cpsp.TokenDetailRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='cpsp.TokenDetailRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=64,
)


_TOKENLISTREQUEST = _descriptor.Descriptor(
  name='TokenListRequest',
  full_name='cpsp.TokenListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='offset', full_name='cpsp.TokenListRequest.offset', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_items', full_name='cpsp.TokenListRequest.num_items', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=119,
)


_TOKENCREATIONREQUEST = _descriptor.Descriptor(
  name='TokenCreationRequest',
  full_name='cpsp.TokenCreationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='cpsp.TokenCreationRequest.uid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='cpsp.TokenCreationRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=170,
)

DESCRIPTOR.message_types_by_name['TokenDetailRequest'] = _TOKENDETAILREQUEST
DESCRIPTOR.message_types_by_name['TokenListRequest'] = _TOKENLISTREQUEST
DESCRIPTOR.message_types_by_name['TokenCreationRequest'] = _TOKENCREATIONREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TokenDetailRequest = _reflection.GeneratedProtocolMessageType('TokenDetailRequest', (_message.Message,), {
  'DESCRIPTOR' : _TOKENDETAILREQUEST,
  '__module__' : 'msp_pb2'
  # @@protoc_insertion_point(class_scope:cpsp.TokenDetailRequest)
  })
_sym_db.RegisterMessage(TokenDetailRequest)

TokenListRequest = _reflection.GeneratedProtocolMessageType('TokenListRequest', (_message.Message,), {
  'DESCRIPTOR' : _TOKENLISTREQUEST,
  '__module__' : 'msp_pb2'
  # @@protoc_insertion_point(class_scope:cpsp.TokenListRequest)
  })
_sym_db.RegisterMessage(TokenListRequest)

TokenCreationRequest = _reflection.GeneratedProtocolMessageType('TokenCreationRequest', (_message.Message,), {
  'DESCRIPTOR' : _TOKENCREATIONREQUEST,
  '__module__' : 'msp_pb2'
  # @@protoc_insertion_point(class_scope:cpsp.TokenCreationRequest)
  })
_sym_db.RegisterMessage(TokenCreationRequest)



_TOKENS = _descriptor.ServiceDescriptor(
  name='Tokens',
  full_name='cpsp.Tokens',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=173,
  serialized_end=349,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetTokenList',
    full_name='cpsp.Tokens.GetTokenList',
    index=0,
    containing_service=None,
    input_type=_TOKENLISTREQUEST,
    output_type=types__pb2._TOKEN,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetToken',
    full_name='cpsp.Tokens.GetToken',
    index=1,
    containing_service=None,
    input_type=_TOKENDETAILREQUEST,
    output_type=types__pb2._TOKEN,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateToken',
    full_name='cpsp.Tokens.CreateToken',
    index=2,
    containing_service=None,
    input_type=_TOKENCREATIONREQUEST,
    output_type=types__pb2._TOKEN,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TOKENS)

DESCRIPTOR.services_by_name['Tokens'] = _TOKENS

# @@protoc_insertion_point(module_scope)
